name: movie_discovery
description: "A comprehensive Movie Discovery app with Clean Architecture"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  path: ^1.9.0

  # Environment Variables
  flutter_dotenv: ^5.2.1

  # UI & Animations
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.2.0
  pod_player: ^0.2.1
  url_launcher: ^6.3.1

  # Authentication
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.4

  # Utils
  intl: ^0.20.1
  dartz: ^0.10.1
  connectivity_plus: ^6.1.1
  internet_connection_checker_plus: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  injectable_generator: ^2.4.4
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
    - .env
